name: Recipe Maker
description: Converts ipynb into PDF
inputs:
  paper-path:
    description: Path to the jupyter notebook
    required: false
    default: 'recipe.ipynb'
runs:
  using: docker
  image: 'docker://jupyter/minimal-notebook:latest'
  entrypoint: "bash"
  args:
    - -c # needed for logging
    - |
      JOSS_PATH=${{ inputs.paper-path }};
      JOSS_FOLDER="$(readlink -f "$(dirname "${{ inputs.paper-path }}")")"
      IPYNB_FILE="$JOSS_FOLDER/recipe.ipynb"
      PDF_FILE="$JOSS_FOLDER/paper.pdf"
      jupyter nbconvert --to pdf $IPYNB >> /home/jovyan/work/a.txt
      mv "$JOSS_FOLDER/recipe.pdf" PDF_FILE
      echo "$( < /home/jovyan/work/a.txt )" # This outputs to github action logs.




