name: Recipe Maker
description: Converts ipynb into PDF
inputs:
  paper-path:
    description: Path to the jupyter notebook
    required: false
    default: 'recipe.ipynb'
runs:
  using: docker
  image: 'docker://jupyter/minimal-notebook:latest'
  entrypoint: "bash"
  args:
    - |
      ls
      echo $?
      ls /tmp
      echo $?
      ls tmp
      echo $?
      jupyter nbconvert --to pdf ${{ inputs.paper-path }}
      echo $?

#&& mv /home/jovyan/work/*.pdf /github/workspace/




