name: Recipe Maker
description: Converts ipynb into PDF
inputs:
  paper-path:
    description: Path to the jupyter notebook
    required: false
    default: 'recipe.ipynb'
runs:
  using: docker
  image: 'docker://jupyter/minimal-notebook:latest'
  entrypoint: "bash"
  args:
    - -c
    - |
      jupyter nbconvert --to pdf ${{ paper-path }} >> /home/jovyan/work/a.txt
      echo "$( < /home/jovyan/work/a.txt )"




