name: Recipe Maker
description: Converts ipynb into PDF
inputs:
  paper-path:
    description: Path to the jupyter notebook
    required: false
    default: 'recipe.ipynb'
runs:
  using: docker
  image: 'docker://jupyter/minimal-notebook:latest'
  entrypoint: "bash"
  args: 
    - /bin/bash
    - -c
    - |
      cp "${{ inputs.paper-path }}" /home/jovyan/work/
      cd /home/jovyan/work
      jupyter nbconvert --to pdf "$(basename "${{ inputs.paper-path }}")"

#&& mv /home/jovyan/work/*.pdf /github/workspace/




